### ISSUE TITLE
[C#] Regression on 0.5.0 with DML

### ISSUE THREAD

**Issue by azchohfi** [microsoft/onnxruntime-genai#1071]
**Describe the bug**
C# Version 0.5.0 broke DML models, such as microsoft--Phi-3-mini-4k-instruct-onnx directml-int4-awq-block-128.
The model loads, but the Generator's constructor throws an Access violation exception.

**To Reproduce**
1. Try running [Phi3 Sample](https://github.com/microsoft/onnxruntime-genai/tree/main/examples/csharp/HelloPhi) with DML
2. Exception line [98](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/csharp/HelloPhi/Program.cs#L98)

**Expected behavior**
Works just as 0.4.0.

**Desktop (please complete the following information):**
 - OS: Windows 11 (24H2)

**Comment by elephantpanda** [comment]
Well, DML [didn't really work before](https://github.com/microsoft/onnxruntime-genai/issues/833) . I mean it works up to a point then breaks.
I was just about to update to 0.5 myself. Thanks for the warning. 🥲

**Comment by elephantpanda** [comment]
Just updated my code to 0.51 to try it out c# directml.
After loading the model it crashes.

**Comment by skyline75489** [comment]
@RyanUnderhill This is the one we caught with the validation pipeline. I thought it was the same error but turns out it wasn't. This crash is reason why there's no log message printed. I can reproduce this locally.

**Comment by skyline75489** [comment]
Seems to be related to the newly added adapter API:

![Image](https://github.com/user-attachments/assets/769f12bf-6e73-417b-ae0c-7aa728e1c29e)

**Comment by skyline75489** [comment]
I'm seeing this with debugger attached:

```plaintext
Non-zero status code returned while running LayerNormalization node. Name:'LayerNorm_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2494)\onnxruntime.dll!00007FFE9D0A7425: (caller: 00007FFE9D0A6A8F) Exception(3) tid(3d68) 80070057 The parameter is incorrect.
```

**Comment by jiaxuwu2021** [comment]
We get very similar error/exception since **`v0.4.0`** of `Microsoft.ML.OnnxRuntimeGenAI.DirectML` nuget package
`2024-11-19T13:58:49.3749334+08:00 An unhandled exception has occurred while executing the request. error: [Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(353)\onnxruntime.dll!00007FFCC8BA254C: (caller: 00007FFCC8B9B7CF) Exception(1) tid(240c) 80070057 The parameter is incorrect.
,    at Microsoft.ML.OnnxRuntimeGenAI.Generator.ComputeLogits()`

also fail to run with **v0.5.0** or **v0.5.1**, but all good if downgrade `Microsoft.ML.OnnxRuntimeGenAI.DirectML` to `v0.3.0`.

**Comment by skyline75489** [comment]
@elephantpanda  Is the crash in `0.5.1` or `0.5.0`? We had some progress but we might need more to fix.

**Comment by azchohfi** [comment]
For our scenario, downgrading from 0.5.1 to 0.5.0 fixed the issue, so @elephantpanda is probably having a separate issue.

**Comment by elephantpanda** [comment]
> [@elephantpanda](https://github.com/elephantpanda) Is the crash in `0.5.1` or `0.5.0`? We had some progress but we might need more to fix.

I am using 0.5.1
![Image](https://github.com/user-attachments/assets/df158c4b-753e-4116-8996-be4c524b9974)

**Comment by skyline75489** [comment]
@elephantpanda You could try 0.5.0 first. We're preparing a 0.5.2 patch release that should fix the crash.

**Comment by elephantpanda** [comment]
I installed 0.5.0 onnxruntimegenai.directml and onnxruntimeGenai.managed

It now doesn't crash. It just outputs the first token then fails on the second token:

`OnnxRuntimeGenAIException: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\execution_frame.cc:173 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,32,12,96} Requested shape:{1,32,2048,96}`

**Comment by jiaxuwu2021** [comment]
Unfortunately v0.5.2 is still not working to me
`Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(353)\onnxruntime.dll!00007FF825C04F3C: (caller: 00007FF825BFE1CF) Exception(3) tid(e25c) 80070057 The parameter is incorrect.`
`at Microsoft.ML.OnnxRuntimeGenAI.Generator.ComputeLogits()`

I found a workaround, add this property to csproj
```
<PropertyGroup>
  <SelfContained>true</SelfContained>
</PropertyGroup>
```
or add this one to csproj
```
<PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
</PropertyGroup>
```

and then clean/rebuild the whole project

**Comment by skyline75489** [comment]
@jiaxuwu2021 This looks similar to #833

**Comment by elephantpanda** [comment]
> [@jiaxuwu2021](https://github.com/jiaxuwu2021) This looks similar to [#833](https://github.com/microsoft/onnxruntime-genai/issues/833)

I can't see the similarity. #833 is to do with certain prompts failing.

**Comment by ambroser53** [comment]
> Unfortunately v0.5.2 is still not working to me `Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(353)\onnxruntime.dll!00007FF825C04F3C: (caller: 00007FF825BFE1CF) Exception(3) tid(e25c) 80070057 The parameter is incorrect.` `at Microsoft.ML.OnnxRuntimeGenAI.Generator.ComputeLogits()`
> 
> I found a workaround, add this property to csproj
> 
> ```
> <PropertyGroup>
>   <SelfContained>true</SelfContained>
> </PropertyGroup>
> ```
> 
> or add this one to csproj
> 
> ```
> <PropertyGroup>
>     <PlatformTarget>x64</PlatformTarget>
> </PropertyGroup>
> ```
> 
> and then clean/rebuild the whole project

This works with main currently to fix some of my models (i.e. Qwen2.5-1.5B in fp16) but not with others. i.e. with Qwen2.5-7B in int4 I get this other (similar) error:

`2024-12-16 11:09:00.3839541 [E:onnxruntime:onnxruntime-genai, sequential_executor.cc:505 onnxruntime::ExecuteKernel] Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\AbiCustomRegistry.cpp(519)\onnxruntime.dll!00007FFC98A186C6: (caller: 00007FFC98A4D69D) Exception(3) tid(3ba0) 80070057 The parameter is incorrect.`

notice that the error is taking place at `AbiCustomRegistry.cpp(519)` instead. Is there any known fix for this? I can send the models in question plus code and/or dlls if anyone thinks they can investigate a fix.
