### ISSUE TITLE
Endless response using the Phi-4-mini-instruct model

### ISSUE THREAD

**Issue by f2bo** [microsoft/onnxruntime-genai#1450]
I'm experiencing problems using the [Phi-4-mini-instruct](https://huggingface.co/microsoft/Phi-4-mini-instruct-onnx) model where it will generate responses that begin to repeat text until `max_length` is reached. 

**To Reproduce**
I see this problem with my application, currently using the `OnnxRuntimeGenAIChatClient`, but also with the sample applications in this repo, for example, the [HelloPhi app](https://github.com/microsoft/onnxruntime-genai/tree/main/examples/csharp/HelloPhi). 

To reproduce it, execute this app using the `cpu` execution provider and the [Phi-4-mini-instruct](https://huggingface.co/microsoft/Phi-4-mini-instruct-onnx) model using the prompt **"_Explain how lasers work_"**. 

> **Note:** You may need to increase the `max_length` value (e.g. to 750) to see the problem as the response to this prompt from some models sometimes exceeds the hard-coded value.
https://github.com/microsoft/onnxruntime-genai/blob/c6ee481d998f1ae34a654f22ab92a9732c5520e0/examples/csharp/HelloPhi/Program.cs#L93

Run:
```
HelloPhi -m E:\models\Phi-4-mini-instruct-onnx\cpu_and_mobile\cpu-int4-rtn-block-32-acc-level-4 -e cpu
```
This results in the following output (only showing bottom lines for the screenshot).

![Image](https://github.com/user-attachments/assets/039eab40-c90b-40f1-9596-d2f78062067c)

**Expected behavior**
Response should end normally.

**Desktop:**
 - OS: Windows 11
 - Browser: NA

**Additional context**

The problem does not exist running the HelloPhi app with a different model, for example, [Phi-3-mini-128K-instruct](https://huggingface.co/microsoft/Phi-3-mini-128k-instruct-onnx)

I also noticed that the problem does not seem to exist in the [Python sample chat app](https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/model-chat.py). After some digging, I narrowed the difference to the prompt template being used.

The HelloPhi app uses the following template:

https://github.com/microsoft/onnxruntime-genai/blob/c6ee481d998f1ae34a654f22ab92a9732c5520e0/examples/csharp/HelloPhi/Program.cs#L119

whereas the Python app uses:

https://github.com/microsoft/onnxruntime-genai/blob/c6ee481d998f1ae34a654f22ab92a9732c5520e0/examples/python/model-chat.py#L53

Notice that besides the newline characters, which do not seem to matter, there's a single space character following the **{input}** placeholder. Adding this single space character to the prompt in the HelloPhi app seems to fix the problem. Alternatively, the problem is also reproducible in the Python code if the space character is removed.

Perhaps this is a known problem and was it was purposely added to the Python code, though it seems quite unexpected.

**Comment by f2bo** [comment]
After further testing, it now appears that the space character in the prompt appears to be unrelated as I continue to see the problem with or without it, which I suppose is not all that surprising.

**Comment by jiafatom** [comment]
This is a known issue. You need use latest onnxruntime-genai model builder to regenerate the model (select k_quant_mixed as quantization algo), and use latest onnxruntime-1.22 (we just released) to run it.

**Comment by f2bo** [comment]
@jiafatom 
> This is a known issue. You need use latest onnxruntime-genai model builder to regenerate the model (select k_quant_mixed as quantization algo), and use latest onnxruntime-1.22 (we just released) to run it.

I don't know if I followed your instructions correctly but I still see the problem with the regenerated model. This is the command line I used to run the model builder. **Can you confirm if it is correct?**

```
python -m onnxruntime_genai.models.builder -m microsoft/Phi-4-mini-instruct -o ./models/microsoft/cpu_and_mobile/phi4-mini-regenerated -p int4 -e cpu --extra_options int4_algo_config=k_quant_mixed
```

Note that I had to use onnxruntime-1.21.1 to run model builder as I was getting the following error with onnxruntime-1.22.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\ModelBuilder\.venv\Lib\site-packages\onnxruntime_genai\models\builder.py", line 12, in <module>
    from onnxruntime.quantization.matmul_4bits_quantizer import MatMul4BitsQuantizer, QuantFormat
ModuleNotFoundError: No module named 'onnxruntime.quantization.matmul_4bits_quantizer'
```

However, I did run the HelloPhi app with the latest ONNX runtime and the regenerated model. To do this, I added a direct reference to the 1.22.0 package.

```
<ItemGroup>
  <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
  <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" Version="0.7.1" Condition=" '$(Configuration)' == 'Debug' OR '$(Configuration)' == 'Release' " />
  <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.7.1" Condition=" '$(Configuration)' == 'Debug_Cuda' OR '$(Configuration)' == 'Release_Cuda' " />
  <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.7.1" Condition=" '$(Configuration)' == 'Debug_DirectML' OR '$(Configuration)' == 'Release_DirectML' " />
</ItemGroup>
```

![Image](https://github.com/user-attachments/assets/66d8e982-6b73-4b85-ba92-b147446d23d7)

**Comment by jiafatom** [comment]
@f2bo As of today, if you want to regenerate this phi-4 onnx model, you need to build both onnxruntime and onnxruntime-genai from source, because part of k_quant work is not included in onnxruntime 1.22.

After that, this command is good to me: `python -m onnxruntime_genai.models.builder -m microsoft/Phi-4-mini-instruct -o ./models/microsoft/cpu_and_mobile/phi4-mini-regenerated -p int4 -e cpu --extra_options int4_algo_config=k_quant_mixed`

And then when you run the model, you can use onnxruntime 1.22

**Comment by f2bo** [comment]
@jiafatom 

> As of today, if you want to regenerate this phi-4 onnx model, you need to build both onnxruntime and onnxruntime-genai from source, because part of k_quant work is not included in onnxruntime 1.22.

I've never built from source either one. I suspect that it's probably going to take more time than I had originally anticipated. Let me see if I can find the time to give it a try and see how it goes. 

Thanks!

**Comment by f2bo** [comment]
I built the onnxruntime and onnxruntime-genai from source and regenerated the model again and this time there's a difference. I only tested very briefly but prompts that previously resulted in repeating text no longer do so.

I do notice slower performance (about 25% drop in tokens/sec). I don't know if that's expected.

Thanks again!

**Comment by jiafatom** [comment]
@f2bo I think this is expected. Previously it was a pure int4 model (MatMul), now what you generated should be a mixed precision model with some int4 and some int8 (MatMul). Then you should observe slower performance. I haven't checked the number about how much percent drop is expected.

**Comment by jiafatom** [comment]
@f2bo Sure, we are working on some performance improvement, it may help your case. (You may need install onnxruntime from source later to include the new feature)
