### ISSUE TITLE
AttributeError: module 'onnxruntime_genai' has no attribute 'Model'

### ISSUE THREAD

**Issue by iwaitu** [microsoft/onnxruntime-genai#547]
When I run the phi3-qa.py I got some error:

```
(onnx) iwaitu@DESKTOP-RDS3VMA:~/work/onnx$ python phi3-qa.py -m cuda-int4-rtn-block-32
Traceback (most recent call last):
  File "/mnt/d/WSLData/onnx/phi3-qa.py", line 96, in <module>
    main(args)
  File "/mnt/d/WSLData/onnx/phi3-qa.py", line 14, in main
    model = og.Model(f'{args.model}')
AttributeError: module 'onnxruntime_genai' has no attribute 'Model'
```

??!!!

**Comment by natke** [comment]
Hi @iwaitu, can you please list the packages that you have installed?

**Comment by baijumeswani** [comment]
Hi @iwaitu any update here?

The error you're seeing is not expected specially since you're able to successfully import onnxruntime_genai if your code has reached that point.

**Comment by iwaitu** [comment]
@baijumeswani @natke I cant run it with cpu now. thx.

But I still can't run it with cuda.

```
import onnxruntime_genai as og

model = og.Model('cuda/cuda-int4-rtn-block-32')
tokenizer = og.Tokenizer(model)
tokenizer_stream = tokenizer.create_stream()
 
# Set the max length to something sensible by default,
# since otherwise it will be set to the entire context length
search_options = {}
search_options['max_length'] = 2048

chat_template = '<|user|>\n{input} <|end|>\n<|assistant|>'

text = input("Input: ")
if not text:
   print("Error, input cannot be empty")
   exit

prompt = f'{chat_template.format(input=text)}'

input_tokens = tokenizer.encode(prompt)

params = og.GeneratorParams(model)
params.set_search_options(**search_options)
params.input_ids = input_tokens
generator = og.Generator(model, params)

print("Output: ", end='', flush=True)

try:
   while not generator.is_done():
     generator.compute_logits()
     generator.generate_next_token()

     new_token = generator.get_next_tokens()[0]
     print(tokenizer_stream.decode(new_token), end='', flush=True)
except KeyboardInterrupt:
    print("  --control+c pressed, aborting generation--")

print()
del generator
```
I got this message:
```
Traceback (most recent call last):
  File "/home/iwaitu/work/onnx/demo_cuda.py", line 3, in <module>
    model = og.Model('cuda/cuda-int4-rtn-block-32')
onnxruntime_genai.onnxruntime_genai.OrtException: CUDA execution provider is not enabled in this build.
```

**Comment by baijumeswani** [comment]
The problem is that you have both onnxruntime-genai as well as onnxruntime-genai-cuda installed.

Both python packages will install the necessary dlls inside the`onnxruntime_genai` folder in your python site-packages. As a result, depending on the order of installation, you will only have one of the two packages installed.

In your case, it looks like the cpu package dlls has overridden the cuda package dlls causing the error you're seeing. I would recommend uninstalling both of them and only re-installing one of them.

**Comment by iwaitu** [comment]
@baijumeswani  when I run pip uninstall onnxruntime-genai, and run the code again, I got this message:
```
(onnx) (base) iwaitu@DESKTOP-RDS3VMA:~/work/onnx$ /home/iwaitu/anaconda3/envs/onnx/bin/python /home/iwaitu/work/onnx/demo_cuda.py
Traceback (most recent call last):
  File "/home/iwaitu/work/onnx/demo_cuda.py", line 3, in <module>
    model = og.Model('cuda/cuda-int4-rtn-block-32')
AttributeError: module 'onnxruntime_genai' has no attribute 'Model'
```

**Comment by natke** [comment]
We have published support for CUDA 12. Please install using these instructions: https://onnxruntime.ai/docs/genai/howto/install.html#cuda-12

**Comment by iwaitu** [comment]
@natke yes, I can run it with cuda now.

**Comment by hafizurcse** [comment]
I can still see the issue even though I don't have cuda version installed. I have only `onnxruntime-genai` installed and I am trying to run the following block:

```
import onnxruntime_genai as og

model = og.Model('cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4')
tokenizer = og.Tokenizer(model)
tokenizer_stream = tokenizer.create_stream()
 
# Set the max length to something sensible by default,
# since otherwise it will be set to the entire context length
search_options = {}
search_options['max_length'] = 2048

chat_template = '<|user|>\n{input} <|end|>\n<|assistant|>'

text = input("Input: ")
if not text:
   print("Error, input cannot be empty")
   exit

prompt = f'{chat_template.format(input=text)}'

input_tokens = tokenizer.encode(prompt)

params = og.GeneratorParams(model)
params.set_search_options(**search_options)
params.input_ids = input_tokens
generator = og.Generator(model, params)

print("Output: ", end='', flush=True)

try:
   while not generator.is_done():
     generator.compute_logits()
     generator.generate_next_token()

     new_token = generator.get_next_tokens()[0]
     print(tokenizer_stream.decode(new_token), end='', flush=True)
except KeyboardInterrupt:
    print("  --control+c pressed, aborting generation--")

print()
del generator
```
which gets the following error:

```
(yolo8) C:\path\dev\onnxruntime-genai>python pred.py
Traceback (most recent call last):
  File "C:\path\dev\onnxruntime-genai\pred.py", line 3, in <module>
    model = og.Model('cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4')
AttributeError: module 'onnxruntime_genai' has no attribute 'Model'
```
I don't have a cuda version installed as shared below:
```
(yolo8) C:\path\dev\onnxruntime-genai>pip uninstall onnxruntime-genai-cuda
WARNING: Skipping onnxruntime-genai-cuda as it is not installed.
```
